### ISSUE TITLE
Add ability to specify storing path

### ISSUE THREAD

**Issue by anastasiia-bilova** [dmytrostriletskyi/diagrams-yaml#2]
Can you please provide functionality to specify a path to store a generated image?

**Comment by fboaventura** [comment]
@anastasiia-bilova It is somewhat dated, but you may use the `file_name` attribute to the `diagram` and specify your desired path.

```yaml
diagram:
  name: Test
  file_name: /home/user/tmp/my_diagram
  format: png
  ...
```

This will save the file as `/home/user/tmp/my_diagram.png`.
